server:
  port: 7551
spring:
  datasource:
    url: jdbc:h2:file:./mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
    health:
      show-details=always: always